### ISSUE TITLE
Errors do not cause rejection, as documented

### ISSUE THREAD

**Issue by pimterry** [gucheen/fetchql#27]
The docs say:

> If any errors exist(from query response), will reject the promise.

The code for this is here: https://github.com/gucheen/fetchql/blob/07d08bef9b153929fdf3d8ea2d8a0e9faf3e245e/src/index.js#L184-L199

In reality, the promise is only rejected if no data is returned. If data is returned and errors exist, the promise will resolve successfully with the data, ignoring the errors.

**Comment by gucheen** [comment]
Thanks, I've fixed the document
