### ISSUE TITLE
Does this library handle this?  Sample RPC

### ISSUE THREAD

**Issue by rjpalermo1** [gucheen/FetchQL#3]
Hello, sorry for the second post but your library has me hopeful for an answer after a long, hard day doing Google searches.

What I am reading is this library can handle an HTTP RPC call like this....

My published endpoint = `https:mywebserver.com/process` 

can receive and process this actual endpoint: 

`https://webserver.com/service/Process.py?clientId=123456789&deviceId=001&userId=12334455&locationId=34`

Is this correct?  If so, can you give an example of how this looks in an code?  I have to convert about 10 of these.

**Comment by gucheen** [comment]
FetchQL is designed for GraphQL only.
It is not suitable for the scene that you meet.
