### ISSUE TITLE
Distribute unminified/ unbundled code

### ISSUE THREAD

**Issue by gajus** [gucheen/FetchQL#4]
There is no reason to distribute a minified code. Furthermore, there is no reason to distribute a bundled code. All you are doing is preventing common chunk optimisation that could be achieved at the bundler level and increasing the overall script size.

**Comment by gajus** [comment]
@gucheen any updates on this?

**Comment by gucheen** [comment]
@gajus I'm currently working on a new version of FetchQL, it will be a 'pure' version of this tools.
I'm agree with that now building tools are widely used in Web Front-End development.
So, it won't be bundled by default.
Thanks for your suggestion.
