### ISSUE TITLE
What is `operationName` used for?

### ISSUE THREAD

**Issue by teckays** [gucheen/fetchql#7]
I am getting an error like `GraphQLError: Unknown operation named "..."`

I've noticed the object passed to the GraphQL server consists of:
```
{
    operationName: "...",
    query: "...",
    variables: { ... }
}
```

why `operationName` is passed when it should only send `query` and `variables`?

**Comment by gucheen** [comment]
You can refer to GraphQL Docs [http://graphql.org/learn/queries/#operation-name](http://graphql.org/learn/queries/#operation-name)

> The operation name is a meaningful and explicit name for your operation.

**Comment by teckays** [comment]
Git it! Thank you
